name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the feature you would like to see added.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Please describe the solution you'd like to see.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Please describe any additional context or screenshots about the feature request here.
    validations:
      required: false
