const DISPLAY_WHEN = {
  AFTER_AUDIO_PLAYING: 'AFTER_AUDIO_PLAYING',
  BEFORE_AUDIO_PLAYING: 'BEFORE_AUDIO_PLAYING',
};

const CONVERSATION_ACTION = {
  END_INTERACTION: 'END_INTERACTION',
  DISPLAY_TEXT: 'DISPLAY_TEXT',
  INTERRUPT: 'INTERRUPT',
  NARRATED_ACTION: 'NARRATED_ACTION',
  PLAY_AUDIO: 'PLAY_AUDIO',
  SET_TEXT_DISPLAY_ORDER: 'SET_TEXT_DISPLAY_ORDER',
  SILENCE: 'SILENCE',
};

const CLIENT_ACTION = {
  SEND_CANCEL_RESPONSES: 'SEND_CANCEL_RESPONSES',
};

module.exports = {
  DISPLAY_WHEN,
  CONVERSATION_ACTION,
  CLIENT_ACTION,
};
