// source: ai/inworld/voices/base_voice.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var ai_inworld_language_codes_language_codes_pb = require('../../../ai/inworld/language_codes/language_codes_pb.js');
goog.object.extend(proto, ai_inworld_language_codes_language_codes_pb);
var ai_inworld_voices_voices_pb = require('../../../ai/inworld/voices/voices_pb.js');
goog.object.extend(proto, ai_inworld_voices_voices_pb);
goog.exportSymbol('proto.ai.inworld.voices.BaseVoice', null, global);
goog.exportSymbol('proto.ai.inworld.voices.BaseVoice.TtsMetadataCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.inworld.voices.BaseVoice = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ai.inworld.voices.BaseVoice.repeatedFields_, proto.ai.inworld.voices.BaseVoice.oneofGroups_);
};
goog.inherits(proto.ai.inworld.voices.BaseVoice, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ai.inworld.voices.BaseVoice.displayName = 'proto.ai.inworld.voices.BaseVoice';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ai.inworld.voices.BaseVoice.repeatedFields_ = [1,6];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.ai.inworld.voices.BaseVoice.oneofGroups_ = [[100,101]];

/**
 * @enum {number}
 */
proto.ai.inworld.voices.BaseVoice.TtsMetadataCase = {
  TTS_METADATA_NOT_SET: 0,
  ELEVENLABS_METADATA: 100,
  INWORLD_V2_METADATA: 101
};

/**
 * @return {proto.ai.inworld.voices.BaseVoice.TtsMetadataCase}
 */
proto.ai.inworld.voices.BaseVoice.prototype.getTtsMetadataCase = function() {
  return /** @type {proto.ai.inworld.voices.BaseVoice.TtsMetadataCase} */(jspb.Message.computeOneofCase(this, proto.ai.inworld.voices.BaseVoice.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.inworld.voices.BaseVoice.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.inworld.voices.BaseVoice.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.inworld.voices.BaseVoice} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.inworld.voices.BaseVoice.toObject = function(includeInstance, msg) {
  var f, obj = {
    languageCodesList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    gender: jspb.Message.getFieldWithDefault(msg, 3, 0),
    naturalSampleRateHertz: jspb.Message.getFieldWithDefault(msg, 4, 0),
    age: jspb.Message.getFieldWithDefault(msg, 5, 0),
    languagesList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f,
    elevenlabsMetadata: (f = msg.getElevenlabsMetadata()) && ai_inworld_voices_voices_pb.Voice.ElevenLabsMetadata.toObject(includeInstance, f),
    inworldV2Metadata: (f = msg.getInworldV2Metadata()) && ai_inworld_voices_voices_pb.InworldV2Metadata.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.inworld.voices.BaseVoice}
 */
proto.ai.inworld.voices.BaseVoice.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.inworld.voices.BaseVoice;
  return proto.ai.inworld.voices.BaseVoice.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.inworld.voices.BaseVoice} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.inworld.voices.BaseVoice}
 */
proto.ai.inworld.voices.BaseVoice.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addLanguageCodes(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {!proto.ai.inworld.voices.Gender} */ (reader.readEnum());
      msg.setGender(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNaturalSampleRateHertz(value);
      break;
    case 5:
      var value = /** @type {!proto.ai.inworld.voices.Age} */ (reader.readEnum());
      msg.setAge(value);
      break;
    case 6:
      var values = /** @type {!Array<!proto.ai.inworld.language_codes.LanguageCode>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addLanguages(values[i]);
      }
      break;
    case 100:
      var value = new ai_inworld_voices_voices_pb.Voice.ElevenLabsMetadata;
      reader.readMessage(value,ai_inworld_voices_voices_pb.Voice.ElevenLabsMetadata.deserializeBinaryFromReader);
      msg.setElevenlabsMetadata(value);
      break;
    case 101:
      var value = new ai_inworld_voices_voices_pb.InworldV2Metadata;
      reader.readMessage(value,ai_inworld_voices_voices_pb.InworldV2Metadata.deserializeBinaryFromReader);
      msg.setInworldV2Metadata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.inworld.voices.BaseVoice.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.inworld.voices.BaseVoice.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.inworld.voices.BaseVoice} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.inworld.voices.BaseVoice.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLanguageCodesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getGender();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getNaturalSampleRateHertz();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getAge();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getLanguagesList();
  if (f.length > 0) {
    writer.writePackedEnum(
      6,
      f
    );
  }
  f = message.getElevenlabsMetadata();
  if (f != null) {
    writer.writeMessage(
      100,
      f,
      ai_inworld_voices_voices_pb.Voice.ElevenLabsMetadata.serializeBinaryToWriter
    );
  }
  f = message.getInworldV2Metadata();
  if (f != null) {
    writer.writeMessage(
      101,
      f,
      ai_inworld_voices_voices_pb.InworldV2Metadata.serializeBinaryToWriter
    );
  }
};


/**
 * repeated string language_codes = 1;
 * @return {!Array<string>}
 */
proto.ai.inworld.voices.BaseVoice.prototype.getLanguageCodesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.ai.inworld.voices.BaseVoice} returns this
 */
proto.ai.inworld.voices.BaseVoice.prototype.setLanguageCodesList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.ai.inworld.voices.BaseVoice} returns this
 */
proto.ai.inworld.voices.BaseVoice.prototype.addLanguageCodes = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ai.inworld.voices.BaseVoice} returns this
 */
proto.ai.inworld.voices.BaseVoice.prototype.clearLanguageCodesList = function() {
  return this.setLanguageCodesList([]);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.ai.inworld.voices.BaseVoice.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.inworld.voices.BaseVoice} returns this
 */
proto.ai.inworld.voices.BaseVoice.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Gender gender = 3;
 * @return {!proto.ai.inworld.voices.Gender}
 */
proto.ai.inworld.voices.BaseVoice.prototype.getGender = function() {
  return /** @type {!proto.ai.inworld.voices.Gender} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.ai.inworld.voices.Gender} value
 * @return {!proto.ai.inworld.voices.BaseVoice} returns this
 */
proto.ai.inworld.voices.BaseVoice.prototype.setGender = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional int32 natural_sample_rate_hertz = 4;
 * @return {number}
 */
proto.ai.inworld.voices.BaseVoice.prototype.getNaturalSampleRateHertz = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.ai.inworld.voices.BaseVoice} returns this
 */
proto.ai.inworld.voices.BaseVoice.prototype.setNaturalSampleRateHertz = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional Age age = 5;
 * @return {!proto.ai.inworld.voices.Age}
 */
proto.ai.inworld.voices.BaseVoice.prototype.getAge = function() {
  return /** @type {!proto.ai.inworld.voices.Age} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.ai.inworld.voices.Age} value
 * @return {!proto.ai.inworld.voices.BaseVoice} returns this
 */
proto.ai.inworld.voices.BaseVoice.prototype.setAge = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * repeated ai.inworld.language_codes.LanguageCode languages = 6;
 * @return {!Array<!proto.ai.inworld.language_codes.LanguageCode>}
 */
proto.ai.inworld.voices.BaseVoice.prototype.getLanguagesList = function() {
  return /** @type {!Array<!proto.ai.inworld.language_codes.LanguageCode>} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * @param {!Array<!proto.ai.inworld.language_codes.LanguageCode>} value
 * @return {!proto.ai.inworld.voices.BaseVoice} returns this
 */
proto.ai.inworld.voices.BaseVoice.prototype.setLanguagesList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {!proto.ai.inworld.language_codes.LanguageCode} value
 * @param {number=} opt_index
 * @return {!proto.ai.inworld.voices.BaseVoice} returns this
 */
proto.ai.inworld.voices.BaseVoice.prototype.addLanguages = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ai.inworld.voices.BaseVoice} returns this
 */
proto.ai.inworld.voices.BaseVoice.prototype.clearLanguagesList = function() {
  return this.setLanguagesList([]);
};


/**
 * optional Voice.ElevenLabsMetadata elevenlabs_metadata = 100;
 * @return {?proto.ai.inworld.voices.Voice.ElevenLabsMetadata}
 */
proto.ai.inworld.voices.BaseVoice.prototype.getElevenlabsMetadata = function() {
  return /** @type{?proto.ai.inworld.voices.Voice.ElevenLabsMetadata} */ (
    jspb.Message.getWrapperField(this, ai_inworld_voices_voices_pb.Voice.ElevenLabsMetadata, 100));
};


/**
 * @param {?proto.ai.inworld.voices.Voice.ElevenLabsMetadata|undefined} value
 * @return {!proto.ai.inworld.voices.BaseVoice} returns this
*/
proto.ai.inworld.voices.BaseVoice.prototype.setElevenlabsMetadata = function(value) {
  return jspb.Message.setOneofWrapperField(this, 100, proto.ai.inworld.voices.BaseVoice.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ai.inworld.voices.BaseVoice} returns this
 */
proto.ai.inworld.voices.BaseVoice.prototype.clearElevenlabsMetadata = function() {
  return this.setElevenlabsMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.inworld.voices.BaseVoice.prototype.hasElevenlabsMetadata = function() {
  return jspb.Message.getField(this, 100) != null;
};


/**
 * optional InworldV2Metadata inworld_v2_metadata = 101;
 * @return {?proto.ai.inworld.voices.InworldV2Metadata}
 */
proto.ai.inworld.voices.BaseVoice.prototype.getInworldV2Metadata = function() {
  return /** @type{?proto.ai.inworld.voices.InworldV2Metadata} */ (
    jspb.Message.getWrapperField(this, ai_inworld_voices_voices_pb.InworldV2Metadata, 101));
};


/**
 * @param {?proto.ai.inworld.voices.InworldV2Metadata|undefined} value
 * @return {!proto.ai.inworld.voices.BaseVoice} returns this
*/
proto.ai.inworld.voices.BaseVoice.prototype.setInworldV2Metadata = function(value) {
  return jspb.Message.setOneofWrapperField(this, 101, proto.ai.inworld.voices.BaseVoice.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ai.inworld.voices.BaseVoice} returns this
 */
proto.ai.inworld.voices.BaseVoice.prototype.clearInworldV2Metadata = function() {
  return this.setInworldV2Metadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.inworld.voices.BaseVoice.prototype.hasInworldV2Metadata = function() {
  return jspb.Message.getField(this, 101) != null;
};


goog.object.extend(exports, proto.ai.inworld.voices);
